package org.hemit.domain.model.exceptions

class TournamentAlreadyStartedException : Exception()
